install.packages("dplyr")
library(tidyverse)
mechacar_table <- read.csv(file='MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
lm(vehicle_length ~ vehicle_weight + spoiler_angle + ground_clearance + AWD + mpg, data=mechacar_table)
summary(lm(vehicle_length ~ vehicle_weight + spoiler_angle + ground_clearance + AWD + mpg, data=mechacar_table))
suscoils_table <- read.csv(file='Suspension_Coil.csv',check.names=F,stringsAsFactors = F)
total_summary <- suscoils_table %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI),.groups = 'keep')
lot_summary <- suscoils_table %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median=median(PSI),Variance=var(PSI),SD=sd(PSI),.groups = 'keep')
t.test((lot_summary$Mean),mu=mean(total_summary$Mean))
t.test(subset(suscoils_table, Manufacturing_Lot=="Lot1")$PSI,mu=1500)
t.test(subset(suscoils_table, Manufacturing_Lot=="Lot2")$PSI,mu=1500)
t.test(subset(suscoils_table, Manufacturing_Lot=="Lot3")$PSI,mu=1500)
